const Agent = require('./base');
const fs = require('fs');
const path = require('path');

class AIExpert extends Agent {
    constructor() {
        super("AI-Expert");
    }

    async work(context) {
        this.log(`Analyzing requirements for: ${context.project_name}`);
    }

    async generateContentForSite(projectPath, context) {
        this.log("Generating professional content using Gemini models (simulated)...");
        const indexHtml = path.join(projectPath, "index.html");

        // Simulate content generation
        const content = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Professional site generated by BuildSquad">
    <title>${context.title}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>${context.title}</h1>
        <p>Expertly crafted by BuildSquad AI</p>
    </header>
    <main>
        <section id="hero" class="card">
            <h2>Welcome to ${context.title}</h2>
            <p>This is a premium web experience generated with Node.js logic.</p>
            <p>We specialized in delivering high-quality visual and functional designs.</p>
            <br>
            <a href="#" class="btn">Learn More</a>
        </section>
        
        <section id="features" style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 2rem;">
             <div class="card">
                <h3>Feature 1</h3>
                <p>Automated orchestration.</p>
             </div>
             <div class="card">
                <h3>Feature 2</h3>
                <p>Modern Design System.</p>
             </div>
             <div class="card">
                <h3>Feature 3</h3>
                <p>Full Test Coverage.</p>
             </div>
        </section>
    </main>
    <footer>
        <p>&copy; 2026 BuildSquad. All rights reserved.</p>
    </footer>
    <script src="script.js"></script>
</body>
</html>`;

        fs.writeFileSync(indexHtml, content);
        this.log(`Generated HTML at: ${indexHtml}`);

        // Create a dummy script
        const scriptJs = path.join(projectPath, "script.js");
        fs.writeFileSync(scriptJs, `console.log("Welcome to ${context.title}");`);
    }

    async generateTests(projectPath) {
        this.log("Generating unit tests (Jest)...");
        const testDir = path.join(projectPath, "__tests__");
        if (!fs.existsSync(testDir)) fs.mkdirSync(testDir, { recursive: true });

        const pjsonPath = path.join(projectPath, "package.json");
        if (!fs.existsSync(pjsonPath)) {
            // Initialize simple package.json for the sub-project
            const pjson = {
                name: path.basename(projectPath),
                version: "1.0.0",
                scripts: {
                    "test": "jest"
                },
                devDependencies: {
                    "jest": "^29.0.0",
                    "jest-environment-jsdom": "^29.0.0"
                }
            };
            fs.writeFileSync(pjsonPath, JSON.stringify(pjson, null, 2));
        }

        const testFile = path.join(testDir, "site.test.js");
        const testContent = `
/**
 * @jest-environment jsdom
 */

test('Page title should contain meaningful text', () => {
    document.body.innerHTML = \`
    <header>
        <h1>Test Title</h1>
    </header>
    \`;
    const h1 = document.querySelector('h1');
    expect(h1.textContent).toBe('Test Title');
});

test('Basic math sanity check', () => {
    expect(1 + 1).toBe(2);
});
`;
        fs.writeFileSync(testFile, testContent);
        this.log(`Generated tests at: ${testFile}`);
    }
}

module.exports = AIExpert;
